### ISSUE TITLE
Some Laravel Love

### ISSUE THREAD

**Issue by aldoyh** [Nutlope/llamacoder#4]
Dear Amazing Team of LlamaCoder,

First let me salut your magic with this great work, but from my personal experience the "Nextjs cold boot time", of course coming from a PHP world.. but the community is massive.

So, it would really be very much appreciated if you do consider supporting the Laravel framework.

Thank you. #php

**Comment by Nutlope** [comment]
Could be interesting to add in the future! I included this in my future TODOs in the README so closing for now
